---
- name: Prepare logserver
  hosts: log
  become: True
  gather_facts: False
  roles:
    - role: add-host
      ip: 192.168.56.3
      hostname: web
      timezone: Europe/Moscow
    - install-epel
    - audit-server
    - journald-server

- name: Prepare webserver
  hosts: web
  become: True
  gather_facts: False
  roles:
    - role: add-host
      ip: 192.168.56.2
      hostname: log
      timezone: Europe/Moscow
    - install-epel
    - install-nginx
    - rsyslog-config
    - audit-client
    - journald-client
