---
- name: Prepare logserver
  hosts: log
  become: True
  gather_facts: False
  roles:
    - role: add-host
      ip: 192.168.56.3
      hostname: web
      timezone: Europe/Moscow
    - install-epel
    - audit-server
    - journald-server

- name: Prepare webserver
  hosts: web
  become: True
  gather_facts: False
  roles:
    - role: add-host
      ip: 192.168.56.2
      hostname: log
      timezone: Europe/Moscow
    - install-epel
    - install-nginx
    - rsyslog-config
    - audit-client
    - journald-client

# Задача: Все логи с nginx должны уходить на удаленный сервер (локально только критичные)
# * TODO: добавить роль с настройкой nginx.conf на хосте web для выполнения основного задания.
# 1. В файле конфигурации nginx убрать настройку по-умолчанию для логгирования в файл /var/log/nginx/access.log:
#    #access_log  /var/log/nginx/access.log  main;
# 2. Добавить в файл /etc/nginx/nginx.conf новый блок строк:
#    access_log syslog:server=unix:/dev/log,facility=local7,tag=nginx,severity=info main;
#    # Setup logs
#    error_log /var/log/nginx/error.log;
#    error_log syslog:server=unix:/dev/log,facility=local6,tag=nginx_error;
# 3. Добавить правило-исключение в конфигурационный файл /etc/rsyslog.conf для сообщений с содержанием: "web nginx:":
#    :msg, contains, "web nginx:" ~
#
# развернуть еще машину elk
# таким образом настроить 2 центральных лог системы elk и какую либо еще;
# в elk должны уходить только логи нжинкса;
# во вторую систему все остальное.